### ISSUE TITLE
Sync Protocol: use oc:size instead of d:quota-used-bytes when browsing folders

### ISSUE THREAD

**Issue by moscicki** [owncloud/android-library#110]
See: https://github.com/owncloud/client/issues/4459

And compare with: https://github.com/owncloud/android-library/search?utf8=%E2%9C%93&q=quota

**Comment by davivel** [comment]
Thanks, @moscicki . I guess we could clean up that code :) 

Fortunately, oc:size is already read: https://github.com/owncloud/android-library/blob/e7891c4acbe33d2e24cb0e9cc1f7c5e8836643eb/src/com/owncloud/android/lib/common/network/WebdavEntry.java#L182

**Comment by davivel** [comment]
Related to owncloud/android#1655
