### ISSUE TITLE
 The ownCloud server is not configured!

### ISSUE THREAD

**Issue by maimalash** [owncloud/android-library#115]
03-29 14:45:20.484    2583-2728/com.owncloud.android.lib.sampleclient E/ReadRemoteFolderOperation﹕ Synchronized /: The ownCloud server is not configured!
03-29 14:45:20.489    2583-2583/com.owncloud.android.lib.sampleclient E/com.owncloud.android.lib.sampleclient.MainActivity﹕ The ownCloud server is not configured!
03-29 14:45:22.502    2583-2597/com.owncloud.android.lib.sampleclient E/Surface﹕ getSlotFromBufferLocked: unknown buffer: 0xab7d3750

**Comment by tobiasKaminsky** [comment]
Some more information would be helpful.
Please use the issue template which is found in https://github.com/owncloud/android/blob/master/CONTRIBUTING.md

**Comment by davivel** [comment]
Closing due to lack of response.
