### ISSUE TITLE
startRefresh()

### ISSUE THREAD

**Issue by thecompguru** [owncloud/android-library#145]
I'm trying out this sample_client and upload,download,delete works but refresh doesn't.  List view never fills out.  "TODO: operation finished in fail" toast every time.  Is this a known situation?  Doesn't seem like it should be this hard to test out.  Just changed the setup.xml strings except user_agent

**Comment by davivel** [comment]
Mmmm, not expected, but it's a long time since me don't have a look to the sample_client. Let me have a look.

**Comment by davivel** [comment]
I made a fast test and worked for me.

What is the version of your ownCloud server? 

Do you see any error or warning in the server logs when you try to refresh? What about the web server logs?

How do you enter the URL in setup.xml? You should include the path to any .php, no 'remote.php/webdav' in the end or similar. Just something like what you type in your web browser to access, like 'https://[your_domain]/[your_path_to_OC_if_any]'
