### ISSUE TITLE
Security problem with auth token

### ISSUE THREAD

**Issue by diyoyo** [owncloud/android-library#150]
Hi, 
I wanted to avoid having to enter password every time I start the app (because the final purpose is not just for my personal use).
Yet, if I try this:
                    ocClient = OwnCloudClientFactory.createOwnCloudClient(serverUri, activity, true);
                  ocClient.setCredentials(OwnCloudCredentialsFactory.newBearerCredentials(authToken));
                    authToken = ocClient.getCredentials().getAuthToken();

not only do I realize that the authToken is just the non-encrypted password, which prevents me from storing it anywhere on the user's phone, but additionally, it just does not work with the following error:
Credentials cannot be used for basic authentication: com.owncloud.android.lib.common.network.BearerCredentials

Am I doing something wrong?
Thanks.

**Comment by JuancaG05** [comment]
Outdated, closing here 🚀
