### ISSUE TITLE
Expired credentials login falls in loop

### ISSUE THREAD

**Issue by mirrajabi** [owncloud/android-library#176]
Hi, I just started contributing to the owncloud android project and I'm seeing a bug that I can't find the reason behind it:
- After some hours working with app (which I don't think it is relevant to time, since it happened in various situations) it kicks the user out and ask for user's password.
- after entering correct password it goes in but asks for password over and over again.

**Comment by raheemczar** [comment]
Check database table of users

**Comment by mirrajabi** [comment]
@raheemczar what should I be looking for in that?

**Comment by raheemczar** [comment]
May table deleted or modified to not joined users with there passwords

raheem
بتاريخ ٢٤‏/٠٩‏/٢٠١٧ ١٢:٥١ م، جاء من "Mohammad Mirrajabi" <
notifications@github.com>:

**Comment by mirrajabi** [comment]
I don't think thats the problem with the server or database, I can login at the same time in the web application. also if I reinstall the app or logout the user I can log in again easily but the expired session login falls in loop. I guess maybe the password is not being stored or something like this happens.

**Comment by mirrajabi** [comment]
This issue doesn't happen on Stable 2.4.0 version but it happens in latest master branch version

**Comment by mirrajabi** [comment]
any help on how the authentication works or a brief description on the situations that would kick the user out would be appreciated.

**Comment by davigonz** [comment]
> This issue doesn't happen on Stable 2.4.0 version but it happens in latest master branch version

Hi @mirrajabi , first, thank you very much for contributing to the owncloud android project. 

The login loop you describe seems to be a bug included during the development of OAuth2 support and reported in the regression test of 2.5.0 release (https://github.com/owncloud/android/issues/2030)

This bug has been fixed for the 2.5.0 release, which is already merged in master (not published yet), so please get the latest changes and comment me if it works for you. 😉

**Comment by mirrajabi** [comment]
Hi @davigonz, thanks for replying
I read that issue before I post mine, that happens for usernames including space. I'm testing with these usernames "test1", "test2" and it happens after some hours of being logged in.
I don't know why it should kick the user out since there is no token in basic authorization.
Please correct me if I'm wrong.
I've merged [this commit](https://github.com/owncloud/android/commit/fcf485a150c2f1b67385005436f530a19fc29158) with my dev branch which is based on 2.4.0 master  and tested and it didn't work.

**Comment by davigonz** [comment]
Hi @mirrajabi , we have changed many things related to authentication in the last release, I'm not sure if using that commit without other changes we have included before would work for you. Anyway, can you check the Android logs and paste here what is shown just after the user is kicked?

**Comment by mirrajabi** [comment]
@davigonz I've tested latest master branch commit and I guess its working fine, cause after Three days it didn't kick the user out. It used to kick out after some hours. so I will close this issue but if it happened again I'll open it and paste the logs here.
