### ISSUE TITLE
server return code 405

### ISSUE THREAD

**Issue by cl465809880** [owncloud/android-library#177]
when i call this method :  
 
` private void startRefresh() {  `

        ReadRemoteFolderOperation refreshOperation = new ReadRemoteFolderOperation("/uploads/");  

        refreshOperation.execute(mClient, this, mHandler);  

    } 

the server return me code 405 . I don’t know what’s mean , probably httpMethod is incorrect ？ 
can you help me ?
Thank you.

**Comment by davigonz** [comment]
Hi @cl465809880 , 405 code usually indicates that the request method is known by the server but has been disabled or cannot be used for the resource identified. 

Are you sure that /uploads/ folder exists or you have permissions to access to it? If you replace "/uploads/" with "/" do you receive the same code?

**Comment by JuancaG05** [comment]
Outdated, closing here 🚀
