### ISSUE TITLE
Upgrade Jackrabbit-webdav library and thus, deprecated/end-of-life HttpClient 3.1 library

### ISSUE THREAD

**Issue by davigonz** [owncloud/android-library#182]
Our network library is going to need an upgrade since we are currently using Jackrabbit-webdav 2.12.14, which depends on [HttpClient 3.x](http://hc.apache.org/httpclient-3.x/), a pretty old library which is no longer being developed. 

So, before trying to perform a complete [replacement](https://github.com/owncloud/android-library/issues/51) using a different library, we are going to try to upgrade the current one.

**Comment by davigonz** [comment]
@jesmrec @michaelstingl 

I've upgraded the Jackrabbit-webdav library to 2.16 version (November 2017), which depends on HTTP client 4.5.3, and this message appears when building the app: 

`Warning:WARNING: Dependency org.apache.httpcomponents:httpclient:4.5.3 is ignored for debug as it may be conflicting with the internal version provided by Android`

As the warning itself says, there is a conflict between the httpclient to be added with that dependency and the Android one, this is the detailed reason: 

> Google Android 1.0 was released with a pre-BETA snapshot of Apache HttpClient. To coincide with the first Android release Apache HttpClient 4.0 APIs had to be frozen prematurely, while many of interfaces and internal structures were still not fully worked out. As Apache HttpClient 4.0 was maturing the project was expecting Google to incorporate the latest code improvements into their code tree. Unfortunately it did not happen. Version of Apache HttpClient shipped with Android has effectively become a fork. Eventually Google decided to discontinue further development of their fork while refusing to upgrade to the stock version of Apache HttpClient citing compatibility concerns as a reason for such decision. As a result those Android developers who would like to continue using Apache HttpClient APIs on Android cannot take advantage of newer features, performance improvements and bug fixes.

A new project to port Apache HttpClient 4.3 for Android was created but also discontinued.

In this [link](http://hc.apache.org/httpcomponents-client-4.5.x/android-port.html) appears all the information related to the issue and also a link to a project maintained by a contributor.

From my point of view, I would definitely go for a new library, we cannot trust on this anymore.

**Comment by jesmrec** [comment]
at this point, i think we have to start to think in a whole library change. Agreed @michaelstingl ?

**Comment by michaelstingl** [comment]
Okay. Thanks for the research. Let’s go…  👍

**Comment by davigonz** [comment]
> Okay. Thanks for the research. Let’s go… 👍

Closing this then, follow up https://github.com/owncloud/android-library/issues/51
