### ISSUE TITLE
purpose of OC_X_REQUEST_ID ?

### ISSUE THREAD

**Issue by hannesa2** [owncloud/android-library#200]
A general question concerning

https://github.com/owncloud/android-library/blob/d49814c1958823d347b4d8613602ddc302bfeb3a/src/com/owncloud/android/lib/common/OwnCloudClient.java#L175

Why do it needs a unique number OC_X_REQUEST_ID here and client don't save or handle it. 
So from the client side there is no need doing it here. That means only server needs it ?
If yes, the server can give himself the number too ?

**Comment by davigonz** [comment]
You are right @hannesa2 , we  didn't notice that, thanks!
