### ISSUE TITLE
Retrofit ?

### ISSUE THREAD

**Issue by hannesa2** [owncloud/android-library#204]
A common (heretic) question: 

https://github.com/owncloud/android-library/blob/d49814c1958823d347b4d8613602ddc302bfeb3a/src/com/owncloud/android/lib/common/OwnCloudClient.java#L54

Why do a lot of stuff "by hand" and not using [Retrofit](https://github.com/square/retrofit) ?

**Comment by davigonz** [comment]
> Why do a lot of stuff "by hand" and not using Retrofit ?

Because it doesn't fit in our case, most of the requests need WebDAV extension and to support WebDAV and non WebDAV requests we have implemented a wrapper "by hand" to send transparent requests by using OkHttp, the network library under the hood of Retrofit, and Dav4Android.
