### ISSUE TITLE
Readme and third party

### ISSUE THREAD

**Issue by hannesa2** [owncloud/android-library#205]
I guess this is not right any more, when I see dependencies

```
dependencies {
    api 'com.squareup.okhttp3:okhttp:3.10.0'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.2.51"
    implementation 'com.gitlab.ownclouders:dav4android:oc_support'
}
```

> Third party libraries
> 
> ownCloud Android Library uses Apache JackRabbit, version 2.2.5. Copyright (C) 2004-2010 The Apache Software Foundation. Licensed under Apache License, Version 2.0.
> 
> Apache JackRabbit depends on Commons HTTPClient version 3.1 and SLF4j version 1.7.5; both included also. Copyright (C) 2004-2010 The Apache Software Foundation. Licensed under Apache License, Version 2.0.

Or does `com.gitlab.ownclouders:dav4android:oc_support` uses this JackRabbit ?

**Comment by davigonz** [comment]
Yes, Apache JackRabbit is not used anymore so we can delete it from README and third party files

**Comment by davigonz** [comment]
I created a couple of PR to solve this
