### ISSUE TITLE
Q: How to build library in JAR format (for legacy eclipse project)?

### ISSUE THREAD

**Issue by mikedolx** [owncloud/android-library#214]
Hi,

I'm currently working on an eclipse legacy project, that uses the ownCloud library. I want to update the library in the project. To do so i need the library in JAR format. Unfortunately by building with gradle the outcome is in AAR format (at least on Jenkins instance the outcome is AAR). 

I found some information on stackoverflow on how to convert an AAR to a JAR, which is basically extracting the classes.jar from the AAR and renaming it. 
Unfortunately this doesn't seem to work. When i add the ownCloud-library.jar into my project's lib folder, eclipse is able to find all the classes and importing namespaces seems to work. Building the App works too. But as soon as i try to run the app on an emulator i get the following error(s):

    Dx unsupported class file version 52.0
	...while parsing com/owncloud/android/lib/BuildConfig.class
	Dx 1 error; aborting
	Conversion to Dalvik format failed with error 1

After searching a bit on the internet i found a few solutions suggesting to change the JRE version to 1.7 and also the java compliance level to 1.7. But none of these seem to work.

Another solution suggest to create an eclipse project, that references the extracted and renamed classes.jar. I also tried that but then eclipse is not able to resolve the namespaces within the my legacy project.

My thought was, that the above mentioned method to "convert" the AAR to JAR is not correct (or does not create a "dexable" JAR file).

So my first qestion would be: How can i build the ownCloud library with ANT, to get a correctly working JAR file?

I have seen this issue:

	https://github.com/owncloud/android/pull/1621

which was about removing the ANT build from the library. The branch seems not to be available anymore, or? I couldn't find it (git clone complains it cannot find the branch).

I understand that ANT is not supported anymore by this library (for good reasons), but maybe someone can help me to get a working JAR?

Thanks in Advance,

Michael

**Comment by davigonz** [comment]
Hi @mikedolx , I'd highly recommend you to migrate the Eclipse legacy project to Android Studio, is not that difficult and you can follow the steps defined in https://developer.android.com/studio/intro/migrate , **Migrating from Eclipse** section. Otherwise, you will more compatibility projects in the future in my opinion.

**Comment by mikedolx** [comment]
Hi @davigonz thanks for the tip. Guess what i did? 

My project compiles so far and i can test. Thanks again!

**Comment by davigonz** [comment]
> My project compiles so far and i can test. Thanks again!

Glad to hear that, good luck with your project!
