### ISSUE TITLE
git tag name suggestion

### ISSUE THREAD

**Issue by hannesa2** [owncloud/android-library#222]
currently there are such tag names

<img width="407" alt="image" src="https://user-images.githubusercontent.com/3314607/50003167-0bf29700-ffa3-11e8-8a45-95f85d87a0e2.png">

In my point of view they should only include numbers, like **1.0** so other apps can include it like 

	        implementation 'com.github.owncloud:android-library:1.0'

and not like current

	        implementation 'com.github.owncloud:android-library:oc-android-library-0.9.24'

please see https://jitpack.io/#owncloud/android-library

**Comment by hannesa2** [comment]
@davigonz You don't like my suggestion ?

**Comment by davigonz** [comment]
> You don't like my suggestion ?

Yes, is what other projects usually use, I will change it in the library, thanks for the suggestion

**Comment by davigonz** [comment]
Done => https://github.com/owncloud/android-library/releases
