### ISSUE TITLE
Remove redundant use of `HttpClient`

### ISSUE THREAD

**Issue by theScrabi** [owncloud/android-library#378]
With the changes done by  [removing the ok http singleton](https://github.com/owncloud/android-library/issues/357) I also introduced a redundend use of the [`HttpClient` wrapper](https://github.com/owncloud/android-library/blob/master/owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/http/HttpClient.java).

The HttpClient gets introduced to the HttpMethod through the constructor:
https://github.com/owncloud/android-library/blob/9d80a95a884715f9d71aa16f86bd36d0d50bce14/owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/http/methods/HttpBaseMethod.kt#L15-L17

However the `execute()` method of the `HttpMethod` is later called from the `OwnCloudClient` which extends the `HttpClient` wrapper: https://github.com/owncloud/android-library/blob/b96a3e9be332544ca0905c4b9f9e179adee514bd/owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/OwnCloudClient.java#L94-L110

Getting "in touch" twice with the client is redundant and should be removed. Here are two possible solutions:
#### 1. Try to Inject the client from the constructor:
    The HttpClient modifying methods in the `HttpBaseMethod` do not need to be changed: https://github.com/owncloud/android-library/blob/9d80a95a884715f9d71aa16f86bd36d0d50bce14/owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/http/methods/HttpBaseMethod.kt#L110
  But the code calling the `method.execute()` in the `OwnCloudClient` has to be moved to the `HttpMethod`: https://github.com/owncloud/android-library/blob/9d80a95a884715f9d71aa16f86bd36d0d50bce14/owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/OwnCloudClient.java#L95

#### 2. Try to inject the client from the execute method:
    The HttpClient modifying methods in the `HttpBaseMethod` need to be modified: https://github.com/owncloud/android-library/blob/9d80a95a884715f9d71aa16f86bd36d0d50bce14/owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/http/methods/HttpBaseMethod.kt#L110
Instead of modifying the OkHttp client directly we could save the modifications and apply them when calling the `execute(client)` method.
The only change that need to be applied to  `OwnCloudClient` would be that `this` is suplied the the `execution()` method. 

------
Issue: https://github.com/owncloud/android-library/issues/378
Library: https://github.com/owncloud/android-library/pull/427
App: https://github.com/owncloud/android/pull/3353

**Comment by jesmrec** [comment]
Done
