### ISSUE TITLE
Gradle dependency

### ISSUE THREAD

**Issue by jitpack-io** [owncloud/android-library#86]
Hi,

Since it successfully builds on jitpack perhaps its worth adding dependency information to readme:
https://jitpack.io/#owncloud/android-library/oc-android-library-0.9.7

Would make it easier for others to include the library in their projects.

**Comment by AndyScherzinger** [comment]
@davivel this would be something which would be nice for a dev setup like the one I use, since I use gradle and wouldn't have to pull in the subproject into the ownCloud main app :dancer: 

Not sure if the main app uses snapshots during the development phase (I guess so)

**Comment by AndyScherzinger** [comment]
See https://jitpack.io/#owncloud/android-library/-oc-android-library-0.9.11-g5e5aac5-7
As for the master simply use: 
```
dependencies {
    compile 'com.github.owncloud:android-library:-SNAPSHOT'
}
```

**Comment by davivel** [comment]
We will consider.

**Comment by AndyScherzinger** [comment]
My comment is just that in case the Remove ANT PR gets merged and we use gradle only that we could then use the android lib as a dependency as defined above to always have the latest master (while one could still change it to anything else in case one wants to have a certain branch/commit).

Besides we could also think about adding maven deployments to the android lib build to publish it in the maven repo which would just be a nice service to third party app developers so they can then just use a dependency defined in gradle. :)

Nothing of high prio...just some thoughts.

**Comment by jcmontesmartos** [comment]
Hi,

I have been developing an ownCloud client and I have used JitPack. It has been so gratifying to include the library without cloning repo and with few lines of code. Obviously,  in case you want to modify the library or using a local branch, you cannnot use JitPack, but it works for the rest of cases.

I have written a post using the ownCloud library with JitPack, in which you can find some examples.
https://solidgeargroup.com/jitpack-public-repositories-android
